### ISSUE TITLE
Big map down

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#102]
Big map not working.

**Comment by csae8092** [comment]
looks like your commit https://github.com/gfranzini/digEds_cat/commit/8dd6853858b1a9641df69df5ebcf5e202336c9c3 introduced malformed gps coordinates. I guess (hope :) ) that after correcting them, everything should work as before.

**Comment by gfranzini** [comment]
Uh? Weird, I only added three new german institutions with correct coordinates, I didn't touch the others... I'll correct and see what happens.
