### ISSUE TITLE
blank vs 'not provided'

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#107]
Is it possible to leave cells that are blank in the data .CSV file also blank in the web application? At the moment, the application provides misleading information. 
So, in my data .CSV file blank cells are cells that I haven't catalogued yet. Conversely, cells that state 'not provided' are indeed catalogued and indicate that the project does not provide that information.
The application currently treats these cells in the same way (as 'information not provided'), which is incorrect.

**Comment by csae8092** [comment]
Empty cells should be marked as "not catalogued yet" in the app. Please check, if this is actually true and consistent. And we can "not catalogued yet" replace by any more appropriate string any time. Just post it here

**Comment by gfranzini** [comment]
"not catalogued yet" is fine!

**Comment by gfranzini** [comment]
There's a bug in the 'OCR/Keyed' --> it says 'not catalogu'. I can't find its location in the app code or I would change it myself and do a PR.

**Comment by csae8092** [comment]
thanks for noticing!
