### ISSUE TITLE
Redundancy: mirror image

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#115]
Hi, do you already mirror (more or less regularly) the catalogue and your other projects on another server? I would be interested in mirroring the catalogue on our German server as a precaution, but I'm not sure what this entails and what the ACDH permissions are in this regard.
This is not something we need to deal with now but it's worth looking into, I think.

**Comment by csae8092** [comment]
The database storing dig-ed-cat data is incrementally backed up every day and fully every week - I think.
