### ISSUE TITLE
Vectorize catalog data and play with it

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/dig_ed_cat#118]
Shouldn't be too tricky to transform the data of each catalog entry into some normalized numeric vector and to play/analyze the outcomes.

**Comment by csae8092** [comment]
Implemented [https://dig-ed-cat.acdh.oeaw.ac.at/charts/barcharts/?chart=/charts/kmeansjson/](something ) but I am afraid without proper documentation, no one will ever know what this actually means....

**Comment by gfranzini** [comment]
Hmmm, interesting. I've heard of k-means clustering but would need to read up more to understand what it does. Were you just playing around or is there something you would like to do in particular? But, yes, it would be good to start thinking about how else we could use this data. :-)
