### ISSUE TITLE
Location triangulation on the map

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#119]
do you know of any viz or code that would allow us to triangulate geographical information for every edition on a map? For every edition we have: 1) provenance of source material; 2) current location of source material; 3) producing institution. It would be very cool to trace the journey of, say, a manuscript on a map.

The problem, however, is what happens if we have multiple places of provenance, multiple institutions and multiple current repositories for a single edition.

Any suggestions? 
This could be part of the wishlist, seeing as I have to add coordinates for all locations...

**Comment by csae8092** [comment]
This shouldn't be too tricky, either:
1. depicting this information in some network graph, similar maybe to something like [here](https://thun-korrespondenz.acdh.oeaw.ac.at/pages/personperson-net.html)
2. using the gps-coordinates of the institutions to pin the nodes of this graph on a map.

**Comment by gfranzini** [comment]
Excellent!! I will work on the data then.

**Comment by gfranzini** [comment]
Shall we test this on a couple of editions? Where should I add the coordinates of 'current repository' and of 'place of origin'? Should I keep these in separate .csv files or everything in the `institutions_places_enriched.csv` with specific IDs? Let me know what you prefer.

**Comment by gfranzini** [comment]
I was at DH FBK in Trento today and they showed me a tool they developed that we could repurpose for our data triangulation: https://github.com/dhfbk/rambleon-navigator

This here is a demo: http://dhlab.fbk.eu/rambleon/ 
This screenshot shows, for example, Einstein's movements:

![screen shot 2017-09-27 at 19 35 41](https://user-images.githubusercontent.com/5539685/30928195-2b9eaa16-a3bb-11e7-9dfc-624ce781f701.png)
