### ISSUE TITLE
Updating of beginning and ending date sometimes does not work

### ISSUE THREAD

**Issue by rotula** [acdh-oeaw/dig_ed_cat#121]
In the CSV data for beginning and ending date either a string value ("not provided", "present" for ongoing projects) or a four digit year can be provided. The template for the detail view always displays the year, if present, and only shows the string content, if the date entry is NULL.

But the update in editions/views.py `sync_status()` never sets `Edition.begin_date` and `Edition.end_date`to NULL.

To fix this, I propose to explicitly set `Edition.end_date` to NULLl (`None`), when `Edition.end_date_coment` is set, i. e. after the line `temp_ed.end_date_comment = str(row[10])` add `temp_ed.end_date = None`. The same goes for `Edition.begin_date`.

**Comment by rotula** [comment]
Come to think of this isssue and of #120: Why do an update of the data? Why not just clean the whole database whenever you sync? Or is there anything in the database that is not in the CSV files?

**Comment by csae8092** [comment]
Thank you very much for reporting #120  and #121. I applied your suggested path (deleting all edition-objects before syncing) and it seems to do the trick.
