### ISSUE TITLE
Add 'Sahle Catalog' column to project sheets

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#127]
Hi, could you add the last column of the spreadsheet, 'Sahle Catalog', to the individual project sheets? As always, the values are `yes` (1) and `no` (0) and the help-text can be: "The project is present in Sahle's Catalog", where 'Sahle's Catalog' is hyperlinked to this address: http://www.digitale-edition.de

Thanks!

**Comment by gfranzini** [comment]
Hey, the 1 value says TRUE not YES. Example: https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/10

I tried changing it myself in models.py but couldn't find the value to change. Could you turn it to 'yes'? Thank you!

**Comment by zxenia** [comment]
Hi Greta!
I'll do it tomorrow. This thing about true/yes is a bit tricky, it takes, first,  setting up values in choices in models and then calling get_FIELD_display in template.
Also, I think, makes sense to add this field to filtering options.

**Comment by gfranzini** [comment]
Yes, it makes a lot of sense to add it to the filtering options. :-) Thanks!
