### ISSUE TITLE
provide verbose_names for editions/models.py class Edition

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/dig_ed_cat#128]
I created a class which generates filterable (Bar)Charts automatically or each property of class Edition for which a filter is defined ([see](https://dig-ed-cat.acdh.oeaw.ac.at/charts/barcharts/))
To avoid duplication of data we should provide meaningful `verbose_name` attributes for all properties of the `editions/models.py class Edition` (like I did in [this commit](https://github.com/acdh-oeaw/dig_ed_cat/commit/ecebbcd28f442060ff457d71d36f6865e17cfca3))

In case there are filters defined which do not correlate to direct property of an Edition instance (like e.g. `institution__name`) a meaningful `label` attribute should be declared in  `browing/filters.py class EditionListFilter`

**Comment by csae8092** [comment]
charts can now be configured in [chart_config.py](https://github.com/acdh-oeaw/dig_ed_cat/blob/master/charts/chart_config.py). 
* The values provided in `help_text` and `label` show up in the [chart-selector menu](https://dig-ed-cat.acdh.oeaw.ac.at/charts/chartselector/) and are used in the charts as well (for legends, headlines....)
* The values provided in `chart_types'  define, what kind of charts will be available. Currently only the mentioned three are defined

@gfranzini would you like to modify  this config file to your needs and create a pull request after you done?

**Comment by gfranzini** [comment]
Sure!

**Comment by gfranzini** [comment]
Hi, I think we can remove the URL chart. I'm not sure what to do with the manager name chart, whether we should keep it or leave it out. Opinions?

**Comment by csae8092** [comment]
Hi, you can remove a chart by simply commenting out the according lines in the config-file as you can see in [this commit](https://github.com/acdh-oeaw/dig_ed_cat/commit/5e29d0aaf52801b2a2bfc42b4f7ec3e550940221)
I`d remove only those charts for fields which provide unique values for each edition (like ride-review or project-name)

**Comment by gfranzini** [comment]
OK, thanks!
