### ISSUE TITLE
"Detail view": Add permalink / how to cite info

### ISSUE THREAD

**Issue by ingoboerner** [acdh-oeaw/dig_ed_cat#13]
Each edition has it's unique ID in the database. Could you display the ID or a permalink for each edition? The links https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/2 are stable?

**Comment by csae8092** [comment]
I can't say for how long this application will run as it does right now. Also due to a very basic sync functionality to [Gretas Catalogue](https://github.com/gfranzini/digEds_cat) which provides the data, I am pretty sure, that the IDs of the entries won't change after each sync-process.
