### ISSUE TITLE
configure charts via admin-backend

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/dig_ed_cat#134]
Currently charts configurations are stored in a file. This means changing a chart requires a change in the code which cumbersome as well as error prone. Therefore store the chart-config in the database so  it can be managed through django-admin backend. Also modifiy `chart_conf_creator.py` to prefill the charts config-settings.

**Comment by csae8092** [comment]
Charts can now be configured through the back-end:
https://dig-ed-cat.acdh.oeaw.ac.at/admin/charts/chartconfig/

@gfranzini here is a quick description on how to change this configuration

# delete a chart

just delete the according-db entry

# fields

The name of the fields should be quite self explanatory except maybe `Field path` which provides the needed [field lookup](https://docs.djangoproject.com/en/1.11/topics/db/queries/#lookups-that-span-relationships). Changing this (or adding new a new chart config objects) requires therefore some knowledge about the data model.

**Comment by gfranzini** [comment]
Thank you, alles klar!
