### ISSUE TITLE
All coordinates point to one location

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#135]
Hi, I just noticed that all geo coordinates for each project seem to be pointing to the Arabian Sea. I checked my local .csv file and the coordinates there are fine.
A sync issue?

**Comment by csae8092** [comment]
I hate lat/lng and always get it mixed up (but given [this](https://macwright.org/lonlat/) who would not...), though this time, I have no idea why the order was messed up. But for now it should be ok - thanks for noticing!
https://dig-ed-cat.acdh.oeaw.ac.at/editions/detail/208

**Comment by gfranzini** [comment]
Ah! Interesting, good to know. Thanks for fixing it so quickly! :)
