### ISSUE TITLE
Internet Archive 404 handling

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#137]
What are your thoughts about this?

https://blog.archive.org/2013/10/24/web-archive-404-handler-for-webmasters/

**Comment by zxenia** [comment]
It seems very easy to implement, the problem we don't have an error page :)  but once we have, why not. For now I checked the wayback machine did a snapshot of cde just once on March 16.

**Comment by gfranzini** [comment]
I created a 404 page and did a pull request :-)

**Comment by zxenia** [comment]
I added wayback machine code to the error page, but it only will show up under two simultaneous conditions: cde website doesn't have this page anymore and wayback machine has (had made) a snapshot of this exact page. As I said before it doesn't  make snapshots often.

**Comment by zxenia** [comment]
Thanks, Greta! Now we have cute error page!

**Comment by gfranzini** [comment]
Fantastic, thank you Ksenia! :)
