### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#140]
Maybe it also makes sense at this point to remove "Bar Charts" and "Pie Charts" from the "Analyze the data" menu tab?

**Comment by csae8092** [comment]
Tricky thing, I'd delete them, though I am not sure if this is the right way to go in the (not very likely) case, someone might have cited one of those charts.
Maybe you could add one, or two lines to 'Documentation' and explaining, that we got rid of the 'old' charts?

**Comment by gfranzini** [comment]
Sure, I'll do that!

**Comment by csae8092** [comment]
and since we have SadCat404 together with #137 we are quite on the save side
