### ISSUE TITLE
SPARQL-endpoint

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/dig_ed_cat#148]
Set up triple store and implement sparql-query interface with dig-ed-cat application

**Comment by csae8092** [comment]
[DONE](https://dig-ed-cat.acdh.oeaw.ac.at/sparql/query/)

@gfranzini : you can log in to the admin-backend and create new example queries (https://dig-ed-cat.acdh.oeaw.ac.at/admin/sparql/query/) 

@zxenia the layout could be adapted a bit

**Comment by gfranzini** [comment]
This is awesome! Thanks!!
