### ISSUE TITLE
wordclouds

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/dig_ed_cat#15]
What is a DH-Project without wordclouds? Try to implement some based upon data fetched from e.g. title, audience, technologie. Shouldn't bee too hard using some dedicated js-library.

**Comment by csae8092** [comment]
wordcloud implement
https://github.com/acdh-oeaw/dig_ed_cat/commit/be2c3a7022b72a6a59505eab8ad57493c7e3b01a
but needs some fiddling with wordcloud2.js parameter to improve readability

**Comment by gfranzini** [comment]
Can we move these to the "internal" version of website for now? They're not really useful at the moment because they don't show much.
