### ISSUE TITLE
Homepage layout

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#160]
The homepage is getting quite long. What about aligning the logo and the introductory text side-by-side into two columns? So, logo on the left and text on the right?

**Comment by zxenia** [comment]
Hi, Greta! yes, the page looks long, and the picture takes up all screen on a laptop, so I will try to minimize the image and implement new format (something like boxes) for why? what? how?.

**Comment by gfranzini** [comment]
Yes, boxes sound like a nice solution! Thank you :-)
