### ISSUE TITLE
shorten news list

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/dig_ed_cat#162]
> Also, could we shorten the news list so that only the 4-5 most recent posts appear and add an expandable section for older posts?

(moved from #160)

**Comment by csae8092** [comment]
@gfranzini I implemented something, please add some feedback or in case you like it, close the issue

**Comment by gfranzini** [comment]
Love it, really! I would perhaps change the info icon to something more intuitive, maybe the EXPAND icon? http://fontawesome.io/icon/expand/

**Comment by csae8092** [comment]
changed the icon and moved it to the bottom which seemed to more intuitive. @gfranzini please comment or close the issue

**Comment by gfranzini** [comment]
Looks good, thank you! One last addition, if possible, to make sure that users don't overlook the icon: add some *fixed* grey help-text next to the icon saying 'Show all news items'?
That's it. I can't close the issue as I don't have the necessary permissions in this repository :) Thanks for this!

**Comment by zxenia** [comment]
I 'll do it.

**Comment by zxenia** [comment]
done, [commit](https://github.com/acdh-oeaw/dig_ed_cat/commit/75ecb9aa76d71412f77d9f77f4ead06ab6331d78)
