### ISSUE TITLE
Integration with DMMapp?

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#166]
Would it be worth trying to hook us up onto DMMapp?
Project website: https://digitizedmedievalmanuscripts.org/app/#
GitHub repo: https://github.com/SexyCodicology/DMMapp

What I'm thinking is to create a link via our 'Repository of source material' institutions. The benefit would be resource discovery, both ways if DMMapp likes the idea.
I looked at their [JSON file](https://github.com/SexyCodicology/DMMapp/blob/master/js/data.json) but it looks like both us and them would need an institution ID/primary key for the link to happen, correct?

If you think it makes sense, I can contact the developers with the proposal.

**Comment by zxenia** [comment]
I looked into it and we can do it, for us to provide such  JSON file should be very easy. Especially as now we've implemented institution individual page, so this could work as a link for an institution on digedcat website. You can contact them and let us know what info in JSON file exactly we should provide for this to happen. So far, looking at the linked JSON file,  we have it all.

**Comment by gfranzini** [comment]
Super, I sent them an email! Will keep you posted.

**Comment by gfranzini** [comment]
They replied and are very happy to partner up with us! :-)

Basically, it would be cool, for example, to have a button/link next to the repository in [the sheet below](https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/154) saying something like "View institution in DMMapp". 

![screen shot 2018-02-20 at 20 42 27](https://user-images.githubusercontent.com/5539685/36445471-aeec3b0a-167e-11e8-9d2d-1eee9861af68.png)
Clicking on the button would take me here:

![screen shot 2018-02-20 at 20 33 37](https://user-images.githubusercontent.com/5539685/36445264-06c84f40-167e-11e8-8146-7f90c42c7171.png)

The problem is that this page in DMMapp doesn't have its own URL. It's a generic https://digitizedmedievalmanuscripts.org/app/ URL. In order to connect we need a DMMapp URL, correct? Or is there some cool way of circumventing the problem? 

For them adding us is easy because they simply have to add our own edition URL (in this case https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/154) to their JSON data with a button/link like "View digital editions in the Catalogue".

They are open to solutions and recommendations, if you have any. If they need to add URLs/URIs, let me know and I'll tell them :)

Thank you!

**Comment by gfranzini** [comment]
Hi @zxenia @csae8092 ! Not sure you saw this message, so I'm pinging you. If you could confirm this is what they need to do, then I'll inform them and see what's possible at their end.
Thanks!

**Comment by zxenia** [comment]
Hi, thanks for the reminder!
yes, we will need a URL/or an identifier for each institution to resolve it to DMMapp.
I think they definitely have identifiers for each institution, they just don't expose them.
Maybe they have an API? then we can use it to retrieve their institutions and link to ours.

**Comment by gfranzini** [comment]
Thank you Ksenia, I will ask them!
