### ISSUE TITLE
Network visualisation

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#167]
For the network viz you implemented -which is a very cool idea!- I think it would be useful to have:
1. a fixed legend describing what the colours in the graph mean/represent
2. node labels fixed rather than pop-ups for better guidance
3. adding nodes for current repositories as well

Do you agree?

**Comment by zxenia** [comment]
Hi, Greta! I've added a legend.
For the rest, I am looking into it.

**Comment by gfranzini** [comment]
Nice, thank you!! :)

**Comment by zxenia** [comment]
I reworked netviz view:

- put labels outside of nodes overwise the network is too heavy for perception;
- also changed the map view layout to the identical style as netviz view (to be more style-consistent).

Let me know if anything else that needs tuning ;)

**Comment by gfranzini** [comment]
PERFECT!!! THANK YOU!! Nothing else at the moment :)
