### ISSUE TITLE
URL alias?

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#17]
Would it be worth providing an alias or more intuitive URL for the current web app URL? At the TEI conference comments/requests were made on this.

**Comment by csae8092** [comment]
I have to change the URL according to ACDH's naming conventions which are {project-name}.acdh.oeaw.ac.at
Not sure how much more intuitive this might be. As far as the {project-name} is concerned I am open for everything

**Comment by gfranzini** [comment]
yes I thought that might be the case. Never mind then!
