### ISSUE TITLE
gexf button not working

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#172]
When I click on the GEXF netvis button I get a window with this line but no download file:

![screen shot 2018-02-16 at 18 11 58](https://user-images.githubusercontent.com/5539685/36319989-ea9564ac-1344-11e8-8137-d640b734fdb2.png)

**Comment by csae8092** [comment]
What browser are you using, because it looks like the browser tries to render the returned xml as html as it only returns text-nodes.
For me it works in Chrome, Edge, IE and Firefox

**Comment by gfranzini** [comment]
I tried in Firefox, Chrome and Safari but I get the same result.

**Comment by csae8092** [comment]
I am afraid this is related to your machine or some specific settings on it, trying to render everything as HTML besides and content-type settings provided by the server (Content-Type:application/xml; charset=utf-8). So there is nothing I can do here...
