### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#173]
Hi, I get a Server Error (500) on these two pages:

https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/223
https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/224
https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/233

Is it something I can fix?

**Comment by csae8092** [comment]
Thanks for noticing - The problem was that there are no places related to institutions and we didn't take care in the code for such cases. Should be fixed now. Please reopen if not.
