### ISSUE TITLE
Adding RG and OpenAire

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#175]
I'd like to add logos with links to our [ResearchGate](https://www.researchgate.net/project/The-Digital-Editions-Catalogue-App-A-web-application-to-browse-curate-and-analyse-digital-editions) page and to OpenAIRE, which indexes the data [here](https://www.openaire.eu/search/dataset?datasetId=r37b0ad08687::c2ad7b8b5225d5abc748a1c6bbb07aeb).

Should we add these at the bottom with the institutional logos or create an extra card on the homepage with direct links to Twitter, DBIS, OpenAIRE and ResearchGate? Problem is DBIS doesn't have a logo.

Where do you think they would look best?

**Comment by zxenia** [comment]
I think it's better to keep logos in the footer. Institutional logos on the first line and then all social accounts logos we can put below. 
For DBIS we can add just text then (all caps DBIS).

**Comment by gfranzini** [comment]
Can I edit the footer or would you prefer to do it?

OpenAIRE logo with transp background: https://www.openaire.eu/media/com_acymailing/templates/winter/images/OpenAIRE_Logo.png
RG logo with transparent background: https://user-images.githubusercontent.com/511683/28757557-f82cff1a-7585-11e7-9317-072a838dcca3.png
Twitter: https://logos-download.com/169-twitter-logo-download.html/twitter_logo_bird_transparent_png

**Comment by zxenia** [comment]
I can do it. The only thing we need all logos in white with a transparent background, it should be somewhere on these websites in imprint or media section. I already have twitter logo in white for sure.

**Comment by gfranzini** [comment]
Ok i’ll send them to you!

**Comment by zxenia** [comment]
Added all logos, but DBIS, because we don't have its logo, and style text as a logo to fit with other logos is a pain :) we also reference DBIS in 'what' box, so I think it's enough. If not let me know then I'll create a fake logo-text for DBIS.

**Comment by gfranzini** [comment]
I LOVE what you did with the footer. Perfect, as always!
Nah, no need to add DBIS - as you said, we mention it on the homepage already so let's leave it out.
Thank you Ksenia, this is great!

**Comment by zxenia** [comment]
Thanks, Greta :)
