### ISSUE TITLE
Red banner

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#177]
Hi, the red banner won't disappear from [this edition](https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/19) despite the fact that I changed the value to `1`.

**Comment by csae8092** [comment]
Thx for noticing. Looks like the sync script doesn't work properly. I'll look into into, in the mean time I changed the value in the database.

**Comment by gfranzini** [comment]
Thanks! :-)
