### ISSUE TITLE
RSS feed for news

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#179]
Hi, would it be possible to add an RSS feed of our news for users who wish to subscribe to updates?

**Comment by csae8092** [comment]
maybe....

**Comment by csae8092** [comment]
added [rss-feed](https://dig-ed-cat.acdh.oeaw.ac.at/rss/feeds/) 
@gfranzini  please the provided title and description and change them to your needs in here: https://github.com/acdh-oeaw/dig_ed_cat/blob/8b5f49c227c606c0f3a18276c48458db98b138d6/digital_editions/settings/base.py#L126

**Comment by gfranzini** [comment]
The text is fine as it is, no changes required :-) thanks!
