### ISSUE TITLE
Twitter widget deprecation

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#184]
Widgets are being discontinued so our timeline needs to be replaced with the new system: https://twittercommunity.com/t/deprecating-widget-settings/102295

**Comment by gfranzini** [comment]
"On May 25, 2018, the widget settings page will no longer allow embedded timeline widgets to be created or edited. From that date, the only (and best) way to create timeline widgets will be to head to publish.twitter.com 3.0k. All existing timeline widgets that rely on these settings (e.g. the ones that have data-widget-id in the markup) will continue to function until July 27."

**Comment by zxenia** [comment]
from the twitter developers page (the one Greta posted earlier):
 

> The content of the timelines - the Tweets - will be rendered in the same way. **The one notable exception will be search timelines** , which will no longer be rendered in the same way, and will fall back to a simple link that points to the corresponding search results on twitter.com. We hope that your search timeline can be replaced with a user timeline, list timeline, collection timeline, or likes timeline which will offer more fine-grained control over what Tweets show up on your webpage. 

The widget we use (Hashtag search widget) is exactly under this Embedded Search Timeline. As I understood we won't be able to display tweets hashtagged with #DigEdsCat, but we still have other options  like user timeline, list timeline and collection timeline.
The set up we have now will work until July 27.

**Comment by zxenia** [comment]
The twitter widget is already deprecated, so now it displays a button which leads to the search timeline in twitter. I see we have only one option here - 
1. remove the widget from the webpage (we still have twitter icon in the footer which does the same as the button in the widget now).
Let me know if it's ok with you, and I take care of it.

**Comment by gfranzini** [comment]
Fine by me! Thanks for taking care of it :-)
