### ISSUE TITLE
Server error 500 upon syncing

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#197]
Hi guys! 
So I added a new project a few minutes ago but when I click on the `click me to sync` button in the Django application I get a `Server Error (500)` message. 

The last commit is here: https://github.com/gfranzini/digEds_cat/commit/fb6ef038702e2289c468d8f8a1f4f4aa96cc81b8

**Comment by csae8092** [comment]
ok, I removed this mysterious column and run the sync script which worked fine.

**Comment by gfranzini** [comment]
legacy_id? Weird.
Thanks!!!
