### ISSUE TITLE
Country chart

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#22]
Would it be possible to generate a pie/bar chart for countries?

**Comment by csae8092** [comment]
https://dig-ed-cat.eos.arz.oeaw.ac.at/charts/barcharts/?chart=/charts/editionspercountryjson/
https://dig-ed-cat.eos.arz.oeaw.ac.at/charts/piecharts/?chart=/charts/editionspercountryjson/

but be aware that the charts only reflect editions, which are related to institutions from which the gps-coordinates are known

**Comment by gfranzini** [comment]
Thank you! OK, so perhaps this should be specified in the chart caption? For instance:
"Geographical distribution of editions based on producing institutions"

**Comment by csae8092** [comment]
thanks, I changed it accordingly: https://dig-ed-cat.eos.arz.oeaw.ac.at/charts/piecharts/?chart=/charts/editionspercountryjson/
