### ISSUE TITLE
Source text translation field

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#23]
The 'source text translation' field is not displaying contents.

**Comment by csae8092** [comment]
yyyyyyyyyyeeeeessssss, I know. I didn't implemented this field in the sync-script yet due to the heterogenous data this property contains (digits and language codes). But since someone - you -  noticed this now, I fear I have to take care of this... .

**Comment by gfranzini** [comment]
hahaha ok let me know if I can help!

**Comment by csae8092** [comment]
If it is ok for you, I would import the data with the following rules: 
* If there is any lang tag, then this information will be stored in the database (modeled as one to many relation, see [application's data model](https://dig-ed-cat.eos.arz.oeaw.ac.at/datamodel/)
* If there is no information at all or a "0", no information will be stored in the database. This means that from the data stored in the database it won't be possible to distinguish if 
  * a) there is no translation or 
  * b) this information was not provided.

**Comment by gfranzini** [comment]
Thanks for the feedback on this! Rather than leave it ambiguous I would remove the field from the app altogether. People don't seem to use digital editions for translations anyway, so I think it's information we can sacrifice but that will be nevertheless available in the .csv.
