### ISSUE TITLE
"Last synchronised"

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#25]
Would it also be possible to add a "last synchronised: YYYY-MM-DD" line at the bottom of the BROWSE EDITIONS page?

I'll stop bothering you now.

**Comment by csae8092** [comment]
Eeach time a (loged in) user hits "sync" a  `SyncLog`-object with properties `actor`and `sync_date` will be stored. The last of these objects will be displayed at the [BROWSE EDITIONS page](https://dig-ed-cat.eos.arz.oeaw.ac.at/browsing/editions/)
