### ISSUE TITLE
Back/forward arrows disambiguation

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#30]
Hi, following user feedback communicated to me verbally, would it be possible to explicitly state/clarify the role of forward/backward arrows in the app? 
The blue arrows present on every edition page are sometimes misinterpreted as having the same role as browser arrows. Is there a way of making the two different functions clearer? So, blue arrows are used to browse all editions in the order in which they appear in the Catalogue, whereas the browser arrows should be used to navigate back to, for example, a filtered list of editions?

If the best solution is to add some text clarifying the issue, let me know, and I'll write it up!

**Comment by csae8092** [comment]
> If the best solution is to add some text clarifying the issue, let me know, and I'll write it up!
I think this is the best solution. Please @gfranzini  write the text and @zxenia please try to implement it

**Comment by gfranzini** [comment]
"Use the blue _previous/next_ arrows below* to view the projects in the order in which they appear in the Catalogue. If you've reached this page through the filtering options provided in the _Browse Catalogue_ (@zxenia: add HYPERLINK) page, you can navigate back to your filtered list using the _previous/next_ arrows of your browser."

*I wrote 'below' here assuming that the text will appear above every digital edition page. But I can, of course, change it depending on where you'll place the text.

**Comment by csae8092** [comment]
https://dig-ed-cat.acdh.oeaw.ac.at/editions/detail/3 @gfranzini  ok like this? If yes, please close the issue

**Comment by gfranzini** [comment]
Super! Thanks!
