### ISSUE TITLE
Top navigation menu not immediately visible

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#31]
Hi, following user feedback communicated to me verbally, it seems like the top black navigation menu is not immediately visible. Some users click on my name thinking that that will lead them to the Catalogue browser.

Options I propose:
- we keep as it is and I had a line of text at the end of the homepage blurb saying something like "Click HERE to browse the editions or select an option from the black menu bar above"
- we make the menu more visible by changing the colour or its position.

**Comment by csae8092** [comment]
please check and close the issue if it is ok
