### ISSUE TITLE
Incomplete text in IMPRINT page

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#33]
The 'Nature and Purpose of the Business' section contains an incomplete sentence: 
"The project ... (implemented by the ACDH in cooperation with ...) is dedicated to ..."

Is there anything I can do to help?

**Comment by csae8092** [comment]
added "The project dig-ed-cat is dedicated to publish data about digital editions provided by Greta Franzini." @gfranzini  please close the issue if this is ok for you or if not, provide some text

**Comment by gfranzini** [comment]
"The project publishes data provided by Greta Franzini."

Thanks!
