### ISSUE TITLE
Creative Commons Licence values

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#35]
This field should not be binary (yes/no, 1/0). Some editions have CC licences but only for parts of the project, so values like 1.5 should also be accepted.
One recent example is the Tarsian project by the Swiss. At the moment the app says it doesn't have a CC licence but it does, its value in the catalogue .csv is 1.5.

**Comment by csae8092** [comment]
For this I have to change the data model and adapt the import script. This might take a couple of days

**Comment by gfranzini** [comment]
No rush!

**Comment by csae8092** [comment]
Actually "Tarsian project by the Swiss" in CC-license column is now flagged with 0.5 which I'd actually prefer because it is more align with other fields and also from a 'semantically' point of view makes more sense to me, if 1 should be the max (all data under cc)
I'll change the data model and adapt the sync-script

**Comment by gfranzini** [comment]
Sorry, my typo!

**Comment by csae8092** [comment]
Please update the helptext (currently: The values 1 or 0 are used to specify if the project is protected by a Creative Commons License.)
And provide/check the according labels which appear in the filter-dropdown for the cc-field (https://dig-ed-cat.acdh.oeaw.ac.at/browsing/editions/)

**Comment by gfranzini** [comment]
Changes below:

- No Creative Commons License at all used. --> No CC License used.
- CC licences but only for parts of the project. --> CC License (WITH -S and singular) but only for parts of the project.
- Everything under a Creative Commons License. --> Everything under a CC License.
