### ISSUE TITLE
Dead editions label

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#37]
Is there a possibility of adding a red banner to those editions which are no longer available stating "Edition no longer available"? 
For example: n 45 (De Trein der Traagheid) and n 192 (Virginie Lovelings Diary).

**Comment by gfranzini** [comment]
And n 167 (http://ctb.kantl.be/vanhoutte/projects/teleurgang.htm)

**Comment by csae8092** [comment]
This is possible if this information is stored somewhere. As far as I remember there is no column in the csv to store this information yet? In case I missed it please point me to it. In case you plan to implement such a column, please add the column to the end so that the current column order does not change.

**Comment by gfranzini** [comment]
No column yet but I'll add one at the end and update this issue accordingly.

**Comment by gfranzini** [comment]
OK, I added a 'Current availability' column (right at the end of the .csv file), where 1 means STILL AVAILABLE and 0 means DEAD. As I mentioned already, it would be great to visualise the dead editions with a red label but I don't want to overcomplicate things. If it's too tricky, 0 can be visualised as a simple NO.

**Comment by csae8092** [comment]
shouldn't be too difficult, I'll implement something and hoping for feedback

**Comment by csae8092** [comment]
please check https://dig-ed-cat.acdh.oeaw.ac.at/editions/detail/191

**Comment by gfranzini** [comment]
P.E.R.F.E.C.T! One minor correction: NOT > NO = "Edition NO longer available...".
Thanks!
