### ISSUE TITLE
Columns name change

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#38]
I would like to change the following column names:
- Manuscript(s') repository --> Repository of source material
- Manuscript(s') place of origin --> Place of origin of source material

Shall I just change them and inform you? Alternatively, let me know when it's OK for me to do this.

**Comment by csae8092** [comment]
Renaming a column is no problem at all. Just the column order matters. But I just noticed that the information of those two columns is not stored in dig-ed-cat yet.

**Comment by gfranzini** [comment]
OK, good to know! No need to add those yet as they're mostly incomplete.
