### ISSUE TITLE
Menu does not work on Android phone version

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#4]
The menu icon does not display correctly and cannot be clicked. 
I tested the app on a Nexus phone.

**Comment by csae8092** [comment]
yeaaahhhhhhh I know there is something wrong with this menu which is most likley related to the ordering and placing of the responsible css and js libraries. I will look into it.

**Comment by csae8092** [comment]
problem was a wrong identifier in the menu. Should work now
