### ISSUE TITLE
sync function for institutions

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/dig_ed_cat#40]
Implement something which will trigger a sync function for spatial data (institutions)

**Comment by csae8092** [comment]
script updated, tested once, worked. Important to know is that the relation between an edition and an institution object is based upon the string in the institutions names field. Also important to know is, that whenever a name of an institution is changed in the source file and there does not yet exit an institution with exact the same name, a new object will be created. So changing names of institutions could lead to some unused institution objects in the database. No game breaker but also not very nice...

**Comment by gfranzini** [comment]
Thanks for the heads-up, I will be careful.
