### ISSUE TITLE
rearrange nav-bar

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/dig_ed_cat#48]
Since Greta added some new pages, I guess it would make sense to rearrange the navigation menu. I am open for any suggestions and happy about any implementations :)

**Comment by gfranzini** [comment]
Hi both! I'm really sorry for bothering you with all these requests lately. But the project is getting considerable attention, and many of the edits I'm making are the result of user queries and requests (which is great!).
FYI, I plan on adding one final page, called 'FAQ', to list past user requests and answers I've given.

As for the nav arrangement, I would move 'Survey' to the left group and 'FAQ' (when I'm done with it) to the right group. So:
LEFT ("Content" pages): Home-Browse-Analyze-Get-Survey
RIGHT ("Meta pages"): Documentation-FAQ-Imprint-Login/out

I would also add 2017 to 'Survey', so 'Survey 2017'.

But happy to discuss further :-)
Thanks for implementing my commits so promptly, it's really motivating!

**Comment by zxenia** [comment]
Hi, nice to hear that :) I will implement the changes till the end of the week.

**Comment by zxenia** [comment]
I also changed the 'explore' button on main page, I hope you all are ok with new version :) if not let me know.

**Comment by gfranzini** [comment]
Much better, thank you!! :-)
