### ISSUE TITLE
Technical documentation

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#51]
I've been writing up **detailed** documentation of this project for my thesis but have not covered the development part as I'm only involved in the content. Are you documenting the app(s) from a technical perspective? If so, should we merge our two documents in a GitBook and link to it from the app's website? 
My thinking is that the current 'Documentation' page on the app contains essential information, while the GitBook would provide the entire picture for those interested in learning the details.

This is not an urgent task, but we should consider it. What do you think?

**Comment by csae8092** [comment]
if I ever find time to write some more profound documentation, I'd use something like http://www.sphinx-doc.org/en/stable/

**Comment by gfranzini** [comment]
OK!
