### ISSUE TITLE
Twitter feed

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#55]
What do you think about adding a Twitter feed on the website to show updates and new additions to the catalogue? It doesn't have to be a big "widget" (the most recent 3 tweets or a scrollable feed would be sufficient) and I can set-up a short hashtag so that the widget only shows messages that use that hashtag (e.g. digEdsCat).

**Comment by csae8092** [comment]
sure, do you want to provide the widget code? Please feel free to add it to index.html if you want

**Comment by gfranzini** [comment]
OK! Need to decide where best to put it.
