### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#57]
Got this again today when I synced some institution updates: https://github.com/gfranzini/digEds_cat/commit/d243a7345b4c1414eeed8305545c47a0c7438350

**Comment by csae8092** [comment]
problem are the missing values for N/A and Various
`Exception Value: ["'' value must be a decimal number."]`
I'll try to make the sync script slightly smarter...

**Comment by gfranzini** [comment]
Ah! Or could we just use 0 in every field? I just want to be able to display the 'N/A' in the app. I personally don't like 'Various' but it will have to do for now. I will find some time at some point to replace 'Various' with the actual institutions.

**Comment by csae8092** [comment]
nono, this will cause some other issues (like putting points on a map...). And I have to start writing more stable code anywhere instead of quick and dirty hacking.... .
