### ISSUE TITLE
Feature: Map overview

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#61]
Would it be possible to add a 'Map Overview' item to the 'Analyze the Data' drop-down list with the map that is currently only available internally in 'Places'? I would like the Map Overview to display all institutions involved in the creation of digital editions. 

Ideally, but not necessary or urgent, it would be amazing to click on a marker in the map and see the list of projects created by that institution.

**Comment by csae8092** [comment]
yes this should be easy

**Comment by csae8092** [comment]
basic map is implemented, maybe a slightly more intelligent nav-bar entry is needed as well as some more information in the pop ups. Waiting for suggestions

**Comment by gfranzini** [comment]
Beautiful, thanks! Let me play with it and come up with a LOOOOOOOONG requirements list for you :-P

**Comment by gfranzini** [comment]
Suggestions:
- **Navbar**: remove MANAGER NAME, URL, PERIOD, LANGUAGE fields. Keep only EDITION NAME, INSTITUTION NAME, FILTER and RESET SEARCH. I think users are probably only going to use EDITION NAME and INSTITUTION NAME anyway for this particular map. If possible, I would try and make the navbar horizontal rather than vertical and place it above the map. That way it's cleaner and not so tight-looking.
- **Pop-ups**: as mentioned already, it would be nice for the pop-ups to display the list of relevant projects under the institution name. Ideally, the projects would be hyperlinked so that clicking on them in the pop-up would lead the user to the corresponding digital edition window. Does that make sense?

**Comment by gfranzini** [comment]
Awesome, thank you!

**Comment by csae8092** [comment]
as far as the position of the filter menu is concerned. I'd keep it as it is because
- the layout is responsive, so if the screen is too small, the filter section moves on top anyhow
- if someone wants to do some more complex filters, the filter list needs to be expanded and if the list was on top, the map would move very much towards the bottom
Therefore I will close the issue but feel free to play around with the layout and reopen the issue...

**Comment by zxenia** [comment]
Hey I updated a bit a map view, added search options in pop up modal. let me know if you have more comments on that.

**Comment by gfranzini** [comment]
LOVE the pop-up modal, excellent idea! No further comments, just thank you!

**Comment by zxenia** [comment]
Thanks! credits to Peter for modal's idea :)
