### ISSUE TITLE
Institution suggestions bug in browse + map view

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#64]
A user pointed me to a bug. In both browse and map view, if you type 'centrum' in the institution field, three items are suggested when it should be one (Belgian centre for textual editing). This is odd as the institutions csv doesn't have three entries for this institution but one. I remember that a previous version of the institutions csv contained these different versions, which I merged to one. Could it be that the institutions csv is not syncing correctly or is storing past entries?

**Comment by csae8092** [comment]
there were indeed three "centrum ..." in the database. I deleted two of them and synced again. Now it should be fine. 
I guess the reason for this growth of "centrums" is realted to the matter of fact, that our application does only create new objects or modifiy existing ones while syncing but does not delete any objects (which is somehow intended, especially for editions). So I'd say whenever someone notice something similar, just open an Issue and I'll take of it manually.

**Comment by gfranzini** [comment]
Perfect! Thanks!
