### ISSUE TITLE
GitHub sync server error (500)

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#7]
I get a server error (500) when I try to sync the repositories.

**Comment by csae8092** [comment]
there seems to be two problems with the import script:

1. first there are invalid valid in the database like "1 (some)"
2. Change in the db-scheme (at least one column removed), therefore I have to adapt the import script (and the applications data model to reflect this change)

**Comment by csae8092** [comment]
reworked the import script and sync-function works again
