### ISSUE TITLE
Browser tab icon

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#72]
**Very low priority.**
What do you think about having this price-tag as the browser tab icon of the website? It should be recognisable despite the small size and I see it as a good representation of the labelling/cataloguing of the data. 

http://www.flaticon.com/free-icon/price-tag_138238

Alternatively, we could select one of the three squares constituting the catalogue logo but that might not be as descriptive as the price-tag. 
Let me know what you think!

**Comment by csae8092** [comment]
seems to be there are some ccs-issues with the block-quotes: @zxenia could you have a look

**Comment by csae8092** [comment]
do you mean a favicon? I added the dig-ed-cat logo as favcion using http://www.favicon-generator.org/; could be for sure improved, if someone wants to....

**Comment by gfranzini** [comment]
OK, I'll create one with just the squares. I get an undefined white square with illegible writing at the moment.
And yes, something weird is happening with the blockquotes in the user feedback page.

**Comment by gfranzini** [comment]
[345966e2ffaa1d21522f9d09053095e4.ico.zip](https://github.com/acdh-oeaw/dig_ed_cat/files/1001089/345966e2ffaa1d21522f9d09053095e4.ico.zip)

How about this?

**Comment by zxenia** [comment]
Great! I really like it!
