### ISSUE TITLE
Integrate with RIDE reviews

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#74]
What do you think about adding links to RIDE reviews?
For example, our entry https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/107 could be linked to http://ride.i-d-e.de/issues/issue-5/jane-austens-fiction-manuscripts/

Do you like the idea?
If so, I'm not sure whether we should add a fourth column in the 'Browse Editions' page called 'RIDE review' or if we should add it to the individual digital edition page, or both. What do you think?
What would I need to do and where? Would I simply add another column in the master .csv file?

**Comment by csae8092** [comment]
good idea. just add another column at the end of the .csv and I'll update the data model, sync-script.... .

**Comment by gfranzini** [comment]
OK, will do!

**Comment by gfranzini** [comment]
Done. This was super quick as there were only 4 matches.

**Comment by csae8092** [comment]
@zxenia ride review field is implemented but can't be filtered yet. Maybe you can take a look at it

**Comment by gfranzini** [comment]
Looks great, thank you!
