### ISSUE TITLE
Syncing issue edition #249

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#75]
The Mexican institution of https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/249 has not been syncing since yesterday. I checked the spreadsheets and they match.

**Comment by csae8092** [comment]
you mean the data of the edition (if so, could please name the unsynced fields) or the data of the institution?

**Comment by gfranzini** [comment]
I can see you fixed this already. Thanks!
