### ISSUE TITLE
University of Trier vs. Universität Trier

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#79]
'Universität Trier' is still showing up in the institution search box even though the English version is used. Another example of a preserved form that should be deleted.

**Comment by csae8092** [comment]
Hi, I deleted Universität Trier in the backend. Here is the needed link (https://dig-ed-cat.acdh.oeaw.ac.at/admin/editions/institution/), you should be able access it.

**Comment by gfranzini** [comment]
Yes, I'm in! Thank you.
