### ISSUE TITLE
Unicode display

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#8]
![screen shot 2016-08-12 at 15 29 16](https://cloud.githubusercontent.com/assets/5539685/17626334/294da0a2-60ad-11e6-8fe1-0f339cfc3533.png)

Apostrophe doesn't display correctly.

**Comment by gfranzini** [comment]
I'll work on the name consistency in the meantime.

**Comment by csae8092** [comment]
I can't promise if I'll be able to fix this (quickly).

**Comment by csae8092** [comment]
a fix might be introduced by upgrading django-autocomplete-light package which I should do one day...

**Comment by csae8092** [comment]
done with implementation of django-autocomplete-light
