### ISSUE TITLE
simple blog

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/dig_ed_cat#83]
Add a basic blog/CMS so that poor @gfranzini doesn't always hack into to the code like in the 90ies...

**Comment by gfranzini** [comment]
:-)

**Comment by csae8092** [comment]
@gfranzini 
To add new news entries: 
1. log into the admin backend
2. Look for News -> News feeds
3. cllick 'add'
4. fill out the forms, you can use html-tags

**Comment by gfranzini** [comment]
Hey! Thanks for adding the blog :-)
I can't see the NEWS when I log in. I looked everywhere.

**Comment by csae8092** [comment]
can you open this link https://dig-ed-cat.acdh.oeaw.ac.at/admin/news/newsfeed/ ?

**Comment by gfranzini** [comment]
OK, it works! Thanks :-)
