### ISSUE TITLE
'Get institutions and places' submenu tab (under 'Get the Data')

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#93]
Is this tab necessary? I would either remove it or, if we keep it, we should then also provide the digEds_cat.csv file. What do you think?

**Comment by csae8092** [comment]
provide digEds_cat.csv

**Comment by gfranzini** [comment]
OK! Let me know if I can help with this.

**Comment by csae8092** [comment]
the current solution is - from a coding point of view very elegant. But it is not done yet since values from related objects (like institutions) are not fetched.

**Comment by csae8092** [comment]
And while this code works perfectly run locally, running the code on the server it messes up the order of the fields.

**Comment by csae8092** [comment]
https://dig-ed-cat.acdh.oeaw.ac.at/browsing/editions/

**Comment by gfranzini** [comment]
Very cool!! :-D Question: the "alt" message of the download icon says "currently selected editions" --> you mean "all editions" or which selection are you referring to?
