### ISSUE TITLE
Add budget to individual project sheets

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#95]
Could you add the budget column to the individual project sheets? Different currencies are used.  Thanks!

**Comment by csae8092** [comment]
Yes I can! But could you please update this fields description in  https://github.com/gfranzini/digEds_cat/wiki/Data-description-&-contribution because it seems a bit outdated (name of the fields seems to have changed and there is no information about expected values in this field)
Thanks!

**Comment by gfranzini** [comment]
Done! I updated the .csv as well to match the values. I see you added the field already, thanks :-D
