### ISSUE TITLE
rework documentation page

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/dig_ed_cat#96]
as already suggested by @gfranzini [here](https://github.com/acdh-oeaw/dig_ed_cat/pull/94) the [documentation page](https://dig-ed-cat.acdh.oeaw.ac.at/documentation/) could need some rework.

**Comment by gfranzini** [comment]
Something similar to this would be great: https://themes.3rdwavemedia.com/demo/prettydocs/components.html

A fixed sidebar menu would help find information more easily.

**Comment by zxenia** [comment]
Hey, I reworked the docs page, added navigation outline with links for the page. Couldn't do exactly the affix due to some responsiveness issues of the layout with such a long list of sections.

**Comment by gfranzini** [comment]
Thank you, Ksenia, this works perfectly!
