### ISSUE TITLE
'Report' button

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#98]
Another idea. 
What do you think about adding a 'Report a bug or an update for this project ' button in the individual project sheets under the map? By clicking on it, the user is automatically redirected to the Github issues page of my digEds_Cat repository and prompted to create an issue.

**Comment by csae8092** [comment]
no objections - @zxenia would you like to implement this?

**Comment by gfranzini** [comment]
AWESOME! Thank you!!!!! :-)
